name: Build Xcode Project

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Latest Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.6.app

      - name: Build Target
        run: |
          xcodebuild build \
            -project bad_query.xcodeproj \
            -target bad_query \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
